name: Deploy to SFTP

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  SFTP:
    runs-on: ubuntu-latest

    steps:
      # $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#           local_path: './build/*'
          local_path: './*'
          remote_path: '/var/www/html.old/'
          args: '-o ConnectTimeout=5'
